- README.md
Just some notes about the front-end implementation
> Front-end guidance

- README.md
Updated the readme code examples to be PSR2 compliant
> PSR2 compliant code examples

- .editorconfig
- Controller/Component/PrgComponent.php
- Manager.php
- Model/Behavior/SearchBehavior.php
- README.md
- Type/Base.php
- Type/Callback.php
- Type/Finder.php
- Type/Like.php
- Type/Value.php
- composer.json
- psr2
- composer.json
- add editorconfig
> Update composer and psr2

- Manager.php
- Type/Compare.php
Example:
```php
public function searchConfiguration() {
$search = new Manager($this);
$search
->compare('price_from', [
'field' => $this->alias() . '.price',
'operator' => '>='
])
->compare('price_to', [
'field' => $this->alias() . '.price',
'operator' => '<='
]);
return $search;
}
```
> Adding a compare type.

- README.md
- src/Model/Behavior/SearchBehavior.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
This avoid collision with other search options like 'group' etc.
> Allowing nesting search query under 'search' key.

- src/Type/Base.php
- src/Type/Callback.php
- src/Type/Compare.php
- src/Type/Finder.php
- src/Type/Like.php
- src/Type/Value.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
> Allow skipping finders with with empty value in query string.

- README.md
Organised the setup sections more logically. Added more comments to code sections to make specific things clearer. Added a note about the filterEmpty option. Added some more guidance on how to structure the setup
Tweaks to the comment length which were not wrapping nicely on Github. Also fixed minor typos and added some clarification.
A quick link to how it looks rendered, https://github.com/davidyell/search-1/blob/docs-update/README.md
> Overhauled the docs. 

- src/Model/Behavior/SearchBehavior.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
* Made the config method configurable
* Added a convenience method to get the Manager object
> Minor improvements to the SearchBehavior

- src/Model/Behavior/SearchBehavior.php
> Scrutinizer fixes

- README.md
- src/Manager.php
- src/Model/Filter/Base.php
- src/Model/Filter/Callback.php
- src/Model/Filter/Compare.php
- src/Model/Filter/Finder.php
- src/Model/Filter/Like.php
- src/Model/Filter/Value.php
- tests/TestCase/ManagerTest.php
- tests/TestCase/Model/Filter/CallbackTest.php
- tests/TestCase/Model/Filter/ValueTest.php
Refs #46
I simplified the `loadFilter()` method.
> Fluid manager

- README.md
- src/Model/Filter/Like.php
- tests/TestCase/Model/Filter/LikeTest.php
> Add support for ILIKE.

- src/Controller/Component/PrgComponent.php
- tests/TestCase/Controller/Component/PrgComponentTest.php
> Improve redirection.

- src/Manager.php
- tests/TestCase/ManagerTest.php
> Make search manager use RepositoryInterface instance instead of Table.

- src/Controller/Component/PrgComponent.php
- tests/TestCase/Controller/Component/PrgComponentTest.php
-  Run PRG conversion only for "index" action by default.
-  Allow disabling setting of querystring to request data.
> Prg component

- src/Model/Filter/Compare.php
- src/Model/Filter/Finder.php
I picked up two inaccuracies in method comments of two of the filter classes.  This PR should fix that.  Hope it helps :)
> Fixes to method comments

- README.md
Just fix missing comma in README.md example.
> Fix missing comma in README.md

- README.md
Example on how to persist query strings through filtering
> Example on how to persist query strings

- README.md
- src/Model/Behavior/SearchBehavior.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
Resolves https://github.com/FriendsOfCake/search/issues/84
```php
$articles = $this->paginate($query);
debug($this->Articles->isSearch());
$this->set('isSearch', $this->Articles->isSearch()); 
```
> Allow controller to ask the model for isSearch().

- README.md
- composer.json
- src/Controller/Component/PrgComponent.php
- tests/TestCase/Controller/Component/PrgComponentTest.php
Resolves https://github.com/FriendsOfCake/search/issues/120
I wish there was a more automatic/smarter solution like the cakedc one had, but that would mean more of the logic needs to be moved to the component.
This is a minimal invasive approach to at least support it basically, and support it properly working.
Most importantly it does not include the page by default, which would only lead to big trouble.
> Bugfix keep sorting

- src/Manager.php
- src/Model/Behavior/SearchBehavior.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
Related to: https://github.com/FriendsOfCake/search/issues/117
> Allow multiple filter collections

- src/Manager.php
- tests/TestApp/Model/Filter/TestFilter.php
- tests/TestApp/Model/Table/ArticlesTable.php
- tests/TestApp/Model/Table/CommentsTable.php
- tests/TestApp/Model/Table/FinderArticlesTable.php
- tests/TestApp/Model/Table/GroupsTable.php
- tests/TestApp/Model/TestRepository.php
- tests/TestCase/Controller/Component/PrgComponentTest.php
- tests/TestCase/ManagerTest.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
- tests/TestCase/Model/Filter/BaseTest.php
- tests/TestCase/Model/Filter/BooleanTest.php
- tests/TestCase/Model/Filter/CallbackTest.php
- tests/TestCase/Model/Filter/CompareTest.php
- tests/TestCase/Model/Filter/FinderTest.php
- tests/TestCase/Model/Filter/LikeTest.php
- tests/TestCase/Model/Filter/ValueTest.php
Pretty much what the title says, additional test, some fixes, and a little clean-up work.
> Tests, fixes, and clean-up.

- README.md
Added missing documentation for PR #119
> Updated readme about collection filters

- README.md
Makes typehinting on the manager possible.
> Add typehinting to Table

- README.md
> Update example to use non-deprecated option

- src/Model/Filter/Compare.php
- tests/TestCase/Model/Filter/CompareTest.php
Resolves https://github.com/FriendsOfCake/search/pull/132
> OR config param added to Compare

- src/Model/Filter/Base.php
This would technically speaking break BC on the `query` method.
> Use query interface to allow for other data sources

- README.md
- src/Model/Filter/Base.php
- src/Model/Filter/Boolean.php
- src/Model/Filter/Value.php
- tests/TestCase/Model/Filter/BaseTest.php
- tests/TestCase/Model/Filter/BooleanTest.php
Adds multi field support to the boolean filter too, now things should be complete.
> Complete multi field search support

- src/Model/Behavior/SearchBehavior.php
- src/Model/Filter/Base.php
- src/Model/Filter/Boolean.php
- src/Model/Filter/Callback.php
- src/Model/Filter/Compare.php
- src/Model/Filter/Finder.php
- src/Model/Filter/Like.php
- src/Model/Filter/Value.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
for a cleaner API.
BC due to kept old methods - just added deprecation doc blocks.
Also fixed valid() to return a proper bool result.
> Replace combined getter/setter

- src/Manager.php
Changes the text of the deprecation message for function collection as 'addCollection' is not available
> Change deprecation message

- composer.json
- src/Controller/Component/PrgComponent.php
- tests/TestCase/Controller/Component/PrgComponentTest.php
> Move query conversion

- README.md
- src/Controller/Component/PrgComponent.php
Resolves https://github.com/FriendsOfCake/search/issues/177
> Fix documentation.

- src/Model/Behavior/SearchBehavior.php
> Call searchManager() through table instance.

- README.md
Completing https://github.com/FriendsOfCake/search/pull/179 for IDE compatability.
Also makes copy and paste from the examples easier.
> Better docs.

- README.md
Replace the use of an inferred magic property for a concrete getter
> Because magic is evil

- README.md
If this is useful to some.
It even [contains exactly that usage as image](https://github.com/dereuromark/cakephp-ide-helper/blob/master/docs/CodeCompletion.md).
> Propose IdeHelper

- README.md
- src/Model/Behavior/SearchBehavior.php
- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
Fix for https://github.com/FriendsOfCake/search/issues/191
> allow non empty string values

- README.md
- composer.json
- src/Model/Behavior/SearchBehavior.php
- src/Model/Filter/Boolean.php
- src/Model/Filter/Value.php
- src/Model/SearchTrait.php
- tests/TestApp/Model/Endpoint/ArticlesEndpoint.php
- tests/TestCase/Model/SearchTraitTest.php
This change adds a trait which can be used in custom repository
classes and adds support for custom repositories to the value and
boolean filters.
Signed-off-by: Marlin Cremers <m.cremers@cvo-technologies.com>
> Add support for searching other datasources

- README.md
Just a small change given the deprecation warning on Form::input to change example to use Form::control
> Form::input is deprecated suggesting change to Form::control

- .gitattributes
- .travis.yml
- composer.json
- src/Controller/Component/PrgComponent.php
- src/Model/Filter/Base.php
- src/Model/Filter/Like.php
- src/Model/SearchTrait.php
- tests/TestApp/Model/Table/FinderArticlesTable.php
- tests/TestCase/Controller/Component/PrgComponentTest.php
- tests/TestCase/ManagerTest.php
- tests/TestCase/Model/Filter/BaseTest.php
- tests/TestCase/Model/Filter/BooleanTest.php
- tests/TestCase/Model/Filter/CallbackTest.php
- tests/TestCase/Model/Filter/CompareTest.php
- tests/TestCase/Model/Filter/FinderTest.php
- tests/TestCase/Model/Filter/LikeTest.php
- tests/TestCase/Model/Filter/ValueTest.php
Resolves https://github.com/FriendsOfCake/search/issues/208
> Closes #208

- src/Model/Filter/Base.php
- src/Model/Filter/FilterInterface.php
Adding an interface for filters.
> Adding a FilterInterface

- docs/README.md
clarify types on callbacks
follow https://github.com/FriendsOfCake/search/commit/8731c04c637198ae0fb37e943f617229a8997931
> indentation and typehints

- docs/README.md
- src/Model/Filter/Base.php
- tests/TestApp/Model/Filter/ArticlesCollection.php
- tests/TestApp/Model/Table/CommentsTable.php
- tests/TestCase/Model/Filter/BaseTest.php
- tests/TestCase/Model/Filter/BooleanTest.php
- tests/TestCase/Model/Filter/CompareTest.php
- tests/TestCase/Model/Filter/ExistsTest.php
- tests/TestCase/Model/Filter/LikeTest.php
- tests/TestCase/Model/Filter/ValueTest.php
Rename filter option "field" to "fields".
> Removed deprecated method Base::field().

- src/Model/Filter/Base.php
> Remove unused methods.

- docs/README.md
- src/Controller/Component/SearchComponent.php
- tests/TestCase/Controller/Component/SearchComponentTest.php
> Rename PrgComponent to SearchComponent

- tests/TestCase/Model/Behavior/SearchBehaviorTest.php
Relates to the unmerged `tests` branch.
> Add test for params flattening by Processor

- docs/README.md
> correct doc link

- docs/README.md
using e.g.
```php
'callback' => function (Query $query, array $args, $manager) {
if ($args['tag'] === '-1') {
$query->find('untagged');
} else {
$query->find('tagged', $args);
}
}
```
> note about custom finders and more complex callback examples

- src/Model/Behavior/SearchBehavior.php
> Fix deprecation error on Cake 4.2.
