FriendsOfCake/search

Controller/Component/PrgComponent.php
Type/Value.php

Two changes here:
1. If you don't provide the search values as post data, you will lose the search form data.
2. If you use `in()` instead of `eq()` you can provide multiple values.

Keep search settings / Multiple search values

---

src/Manager.php
src/Type/Base.php
tests/TestCase/Type/ValueTest.php

Due to existing typhints this change can't be done in a backwards compatible way. Any custom Type classes which extends `Type\Base` will need to be updated.

Move argument with default value to last position.

---

src/Controller/Component/PrgComponent.php
tests/TestCase/Controller/Component/PrgComponentTest.php

Previously it was letting the full request to complete before doing
the redirect. This is becuase it is not allowed to return a response
from the initialize() method

Fixing PrgComponent by making it short-sircuit the response cycle

---

README.md

Remove Country stuff left over from 77f3196f0d01beed5f6a8b4d0c80df361fbac009;
make Usage "like" fields match the documented `title` and `content`

fix copy/paste errors in README

---

README.md
src/Controller/Component/PrgComponent.php
src/Model/Behavior/SearchBehavior.php
tests/TestCase/Controller/Component/PrgComponentTest.php

It has been pretty annoying to repeat the action check over and over in the controllers. Let the component do this automatically for you now.

Made it easy to use PRG with just specific actions.

---

src/Model/Filter/Base.php
tests/TestCase/Model/Filter/BaseTest.php

This fixes problem where filter would be skipped when using 'filterEmpty' => true
and value was "0".

"0" should not be considered as empty.

---

README.md
src/Controller/Component/PrgComponent.php
src/Manager.php
src/Model/Behavior/SearchBehavior.php
src/Model/Filter/Base.php
src/Model/Filter/Compare.php
src/Model/Filter/Finder.php
src/Model/Filter/Like.php
tests/TestCase/Model/Filter/LikeTest.php

Resolves https://github.com/FriendsOfCake/search/issues/82
Classified as bug as currently using wildcard chars as normal text triggers wildcard behavior of DB which is not intended (unless you configure and use those specifically as wildcard chars for your filter).
2nd bug was: When using array input, the LIKE before/after was not working.
There were also no tests for this bug, this is now also fixed.
Also some small code cleanup.

Add char config for LIKE wildcards.

---

src/Model/Behavior/SearchBehavior.php
tests/TestCase/Model/Behavior/SearchBehaviorTest.php

Rename options key "search" to "_search" to allow using filter named "search".
Refs #54

Do away with SearchBehavior::filterParams().

---

README.md
src/Model/Behavior/SearchBehavior.php
tests/TestCase/Model/Behavior/SearchBehaviorTest.php

I don't think it's prudent to allow usage like `find('search', $this->request->url)`. Passing querysting directly as find options is pretty risky thing imo. Keys could easily clash with core options or other custom options of custom finders. A user can for e.g. just tack on `&group=foo` and mess up your query. This patch will force people to always use `find('search', ['search' => $this->request->url])`.
I have also rename key "_search" back to "search" to maintain BC. Don't much value in adding the prefix and making people update their code.

Remove ability to directly pass querystring as find options.

---

src/Model/Filter/Base.php
tests/TestCase/Model/Filter/BaseTest.php

This saves users using Table::aliasField() each time when configuring filters
to avoid "ambiguous column" sql errors.
I'll add / update tests if people like the idea.

Auto alias fields in filters.

---

src/Model/Filter/Base.php
tests/TestCase/Model/Filter/LikeTest.php

Instead of reading the field from the configuration use the method, so that the `aliasFields` setting is respected.
Updated the matching test as well.

Resolves #104

---

README.md

The names of the filters are always spelled with first character uppercase. 
See https://github.com/FriendsOfCake/search/issues/115#issuecomment-244936130

Documentation, filter names are ucfirst()

---

README.md
src/Model/Behavior/SearchBehavior.php
src/Model/Filter/Base.php
src/Model/Filter/Like.php
src/Model/Filter/Value.php
tests/TestCase/Model/Behavior/SearchBehaviorTest.php
tests/TestCase/Model/Filter/BaseTest.php
tests/TestCase/Model/Filter/LikeTest.php
tests/TestCase/Model/Filter/ValueTest.php

This is a first attempt of implementing #77
This change introduces the `modeValue` option in the `Base` filter. Support for it is being implemented in the `Value` and `Like` filters, it doesn't seem to make sense for any other filter, `Boolean` is binary, and for `Comparison` only one value only ever really would have an effect.
The `Base` filter exposes multiple values only in case the `multiValue` option is enabled, otherwise it will fall back to returning the default value, basically treating the arguments as non-existing.
For the `Value` filter, in `or` mode, `IN()` is kept being used, IIRC this is less parser/optimizer heavy than multiple `OR`s. For the `and` mode multiple `AND`s are being used, as for using `IN()` this would require grouping and using `HAVING`, and I'm not sure that …

Add multi-value search support.

---

README.md
src/Model/Filter/Like.php
tests/Fixture/ArticlesFixture.php
tests/TestCase/Model/Filter/LikeTest.php

Alternative to https://github.com/FriendsOfCake/search/pull/150 
I dont like it that this has to be done manually, but so far the autodetecting is not bullet proof and therefore this is probably the safer solution for now.

Manual version: Allow numeric fields to be LIKE searched

---

composer.json

Don't use the misleading word framework for a plugin, and also dont use the exact version as this lies now.

Fix up composer description

---

README.md
src/Controller/Component/PrgComponent.php
tests/TestCase/Controller/Component/PrgComponentTest.php

This came up a few times before as an issue if I recall correctly.
In my case
```php
echo $this->Form->input('search');
echo $this->Form->input('has_missing_translation', ['type' => 'checkbox']);
```
The 0 posted will always result in the URL `?has_missing_translation=0`, which then also affects the isSearch and the reset button in the process.
The empty values should be seen as such (as the CakeDC one did). This is a non-invasive minimal BC safe addition that resolves the issue.

Allow emptyFields for PRG component in order for isSearch to stay correct

---

README.md
src/Model/Filter/Value.php
tests/TestCase/Model/Filter/ValueTest.php

Basically a copy of #135, but complete with tests.
However, I've just noticed that having a mode for the values doesn't seem to make any sense, given that this filter applies an EQ comparison, applying AND to multiple values would never match, as a field can only hold one of the values in such a comparison.
Am I missing something, or did I just made a mistake when I added this initially, and nobody noticed it?

Add multi-field search support to value filter.

---

README.md
src/Manager.php
tests/TestApp/Model/Table/GroupsTable.php
tests/TestCase/ManagerTest.php

Continue https://github.com/FriendsOfCake/search/pull/165
The different return types of useCollection() vs getCollection is especially important to clean up here.

Split combined setters/getters for cleaner API.

---

src/Model/Behavior/SearchBehavior.php
src/Model/Filter/Base.php
src/Model/Filter/Boolean.php
src/Model/Filter/Callback.php
src/Model/Filter/Compare.php
src/Model/Filter/Finder.php
src/Model/Filter/Like.php
src/Model/Filter/Value.php
tests/TestCase/Model/Behavior/SearchBehaviorTest.php
tests/TestCase/Model/Filter/BooleanTest.php
tests/TestCase/Model/Filter/CallbackTest.php
tests/TestCase/Model/Filter/CompareTest.php
tests/TestCase/Model/Filter/FinderTest.php
tests/TestCase/Model/Filter/LikeTest.php
tests/TestCase/Model/Filter/ValueTest.php

After be just bumped the major, I think this should also land in that new version.
It is BC - and improves the API by clearly returning a bool result on process() to indicated if a search filter has been actually applied.
It also simplifies the code since skip() doesnt need to be invoked twice.

Api improvement for isSearch.

---

src/Controller/Component/PrgComponent.php

Now that #173 was merged and allows for having components added in any order, Prg now converts posted _csrfToken and _Token to query params as well. This allows to blacklist those.

Allow to blacklist params like _csrfToken and _Token

---

README.md
src/Model/Behavior/SearchBehavior.php
src/Model/Filter/Base.php
tests/TestCase/Model/Behavior/SearchBehaviorTest.php

This allows filters to deal with dates in the default way the CakePHP FormHelper delivers them, ie:
```php
$dateInRequest = [
'someDate' => [
'year' => '2014',
'month' => '01',
'day' => '13'
]
];
```
which lets me configure my filter like so:
```php
$this->searchManager() ->add('start_date', 'Search.Callback', [
'flatten' => false,
'callback' => function ($query, $args, $filter) {
$arrayKeysExist = function (array $keys, array $arr) {
return !array_diff_key(array_flip($keys), $arr);
};
$parts = $args[$filter->getConfig()['name']];
if ($arrayKeysExist(['year', 'month', 'day'], $parts)) {
$startDate = new Time(date('Y-m-d', strtotime('now')));
$timestamp = $startDate->year($parts['year'])->month($parts['month'])->day($parts['day'])->toUnixString();
$query->where([ …
```

Allow passing un-flattened params to filters (closes #170)

---

README.md

Refs https://github.com/FriendsOfCake/search/pull/183#issuecomment-332667580
This is the correct way that works together with the IDE
Only bad magic, that does not help the developer is evil. In this case the evil is the get + magic string that will result in "mixed" return type and then completely kills the typehinting.
With basic annotating/codecompletion file the property works perfectly, see PR https://github.com/dereuromark/cakephp-ide-helper/pull/56 .
That is how developers are actually getting helped in coding :) not be using get() that will never work.

Revert invalid change and remove unneeded extra annotation

---

README.md
src/Model/Filter/Callback.php
tests/TestCase/Model/Filter/CallbackTest.php

See #186
I return true on void functions for backwards compatibility.
Also mention callback return value in README.md although I'm no native speaker, so it needs review or maybe reword

 Allow callback filter to specify process() return value

---

README.md
src/Controller/Component/PrgComponent.php
tests/TestCase/Controller/Component/PrgComponentTest.php

So far you always had to manually add this in every single controller:
```php
$this->set('_isSearch', $this->Capabilities->isSearch());
```
To allow for 
```php
if (!empty($_isSearch)) {
echo $this->Html->link('Reset', ['action' => 'index'], ['class' => 'button']);
}
```
With the component easily being able to do that by default for the conventional way, this will simplify quite a bit the code here.
You can also configure it, or even disable it completely by passing e.g. false.
What do you think?

Allow _isSearch auto populate

---

tests/TestCase/Controller/Component/PrgComponentTest.php

I've refactored some tests, using:
- `assertNull` instead of strict comparisons with `null` keyword;
- `assertTrue` instead of strict comparisons with `true` keyword;
- `assertFalse` instead of strict comparisons with `false` keyword.

Refactoring tests

---

.gitignore
.travis.yml
README.md
composer.json
src/Model/Filter/Finder.php
tests/TestApp/Model/Table/FinderArticlesTable.php
tests/TestCase/Model/Filter/FinderTest.php

Almost always custom finders require certain keys to be present. And you cannot change that, especially not for plugin finders.
Make custom finders get the right fields via map functionality.
Refs https://github.com/dereuromark/cakephp-tools/pull/200 which needs this functionality.

Finder map

---

README.md
src/Manager.php
src/Model/Filter/FilterCollection.php
src/Model/Filter/FilterCollectionInterface.php
tests/TestApp/Model/Filter/MyTestCollection.php
tests/TestCase/ManagerTest.php
tests/TestCase/Model/Filter/FilterCollectionTest.php

This achieves the lazy loading of filter collection that I had stated in https://github.com/FriendsOfCake/search/issues/224#issuecomment-392764849.
- You can now have filter collection in your app e.g. `App\Model\Filter\MySweetCollection.php`.
Use the `FilterCollection::initialize()` method to setup filters using `FilterCollection::add()`.
- Add search behavior to your table, no need to use search manager to setup filters.
- Specify the collection name in find call e.g. 
`find('search', ['collection' => 'my_sweet', 'search' => $queryParams])`
and viola!.
P.S. Search manager no longer loads filters directly anymore, nor does it maintain array of filters arrays. It only has array of collections now and filter loading is always delegated to the collection.

Lazy load filter collection

---

src/Manager.php
src/Model/Filter/FilterCollection.php
src/Model/Filter/FilterMethodsTrait.php
tests/TestCase/Model/Filter/FilterCollectionTest.php

This allows using the convenience methods for filters on both `Manager` and `FilterCollection` instances.

Add FilterMethodsTrait.

---

README.md

The readme is kinda big, so this pull request aims to mitigate that by adding a contents 'table' of links, to get to specific parts quicker.

Added a basic contents table links

---

README.md
src/Model/Filter/Base.php
src/Model/Filter/Like.php
tests/TestCase/Model/Filter/BaseTest.php

We need the multiValue func for a field:
```php
$searchManager
->like('search', ['field' => ['name', 'issue'], 'multiValue' => true]);
```
Currently in each controller action for this we have to hack it a bit with this:
```php
$searchQuery = $this->request->getQuery();
if (!empty($searchQuery['search'])) {
$searchQuery['search'] = explode('|', $searchQuery['search']);
}
$query = $this->ReleaseGroups->find('search', ['search' => $searchQuery]);
```
Not sure if this can be done differently, a bit cleaner.
But I think given the Base class could handle this easily, a multiValueSeparator would be a useful config addition:
```php
$searchManager
->like('search', ['field' => ['name', 'issue'], 'multiValue' => true, 'multiValueSeparator' => '|']);
```
Allowing us to then DRY config this to be used …

Add multi value separator

---

README.md
phpunit.xml.dist
src/Model/Filter/Finder.php

I need an important small improvement/fix for finder config in search.
I was expecting this to work:
```php
$searchManager
->finder('shop_type', ['finder' => 'bits', 'map' => ['bits' => 'shop_type'], 'type' => 'contain'])
...;
```
As the custom finder needs
$this->find('bits', [..., 'type' => 'contain])
to work as expected.
Now at least this (own config to avoid noise) works:
```php
$searchManager
->finder('shop_type', ['finder' => 'bits', 'map' => ['bits' => 'shop_type'], 'options' => ['type' => 'contain']])
```
updated docs.

Fix finder to allow setting options.

---

LICENSE

This consolidates the license to the de facto standards
- filename
- including the word MIT in header for clarification
- include always valid year range
See e.g. https://github.com/spryker/code-generator/blob/master/LICENSE

Clarify MIT in license, add missing year.

---

.editorconfig
docs/README.md
src/Model/Filter/Boolean.php
src/Model/Filter/Compare.php
src/Model/Filter/Exists.php
src/Model/Filter/FilterCollection.php
src/Model/Filter/FilterMethodsTrait.php
src/Model/Filter/Like.php
tests/TestCase/Model/Filter/ExistsTest.php

Also fixed bad inflection and wrong filter result return value.
We often have to filter by content of rows (filled or not yet filled), and have a dropdown with
```php
// For a specific row field
'' => ' - show all - '
'1' => ' content set '
'0' => ' empty '
```
This Exists one takes the heavy load of a manual custom filter away as this easily does this based on the correct empty comparison for the ORM.
One improvement could be auto-detect of nullValue (schema not null => empty string), but maybe thats a bit too much overhead then.
So I settled for this compromise.
A new minor is OK?

Add Exists filter. 

---

docs/README.md
src/Model/Filter/Base.php

This maintains consistency with argument received by callback of Callback filter.

Pass filter instance too to beforeProcess callback.

---

src/Controller/Component/PrgComponent.php
tests/TestCase/Controller/Component/PrgComponentTest.php

Expands an array that was previously flattened with Hash::flatten():

Allow persisting nested query params (e.g. scoped pagination)

---

docs/README.md

Fix `field` option name in `beforeProcess` example.

---

src/Manager.php

The namespace root of our application starts with a lowercase "u".  When passing a fully qualified class name as in the example below, the "u" is capitalised to "U" as part of the `Inflector::camelize()" call in `src/Manager.php` on line 105:
```php
$accounts = $this->Accounts
->find('search', [
'collection' => AccountsCollection::class,
'search' => $this->getRequest()->getQuery(),
]);
```
The capitalisation of the namespace root obviously results in the class not being findable.
The application-side "fix" for this is to prefix it with a `\`, so that the code becomes `'collection' => '\\' . AccountsCollection::class,` in which case the strings ends up not being camelised in the same manner.  
However, perhaps a fix as implemented in this PR could make more sense for a larger number of …

Don't camelize $name if it's an FQCN

---

.travis.yml

The complex logic killed the coverage it seems.
This simplifies it.
checks should run with highest setting to see deprecations in the language  earlier.

Use dedicated coverage run.

---

src/View/Helper/SearchHelper.php
tests/TestCase/View/Helper/SearchHelperTest.php

We forgot this at the time
When you have passed params, e.g. /controller/index/my-filter?query=xyz
Then the reset link would drop the "my-filter" and create 404s (when the passed params are expected/required).
This fixes it.

Dont drop passed params for reset

---

.github/workflows/ci.yml
.stickler.yml
composer.json
docs/README.md
phpcs.xml
phpstan.neon
src/Command/BakeFilterCollectionCommand.php
src/Model/Filter/Base.php
src/Plugin.php
src/Processor.php
templates/bake/FilterCollection/filter_collection.twig
tests/TestApp/Application.php
tests/TestCase/Command/BakeFilterCollectionCommandTest.php
tests/bootstrap.php
tests/comparisons/Filter/testCustomName.php
tests/comparisons/Filter/testDefault.php
tests/comparisons/Filter/testEmpty.php
tests/comparisons/Filter/testPrefix.php

Replaces https://github.com/FriendsOfCake/search/pull/300 if is green.

Bake task for filter collections

---

docs/README.md
src/Model/Filter/Value.php
tests/TestCase/Model/Filter/ValueTest.php

The multiValue part is nice, but once you have too many values, the URL gets out of hand.
?functional_type=0,1,2,8,10,3,7,5,4,6,11,...........&...
For this I propose the "not" config instead.
Works fine for us locally.
?functional_type=!9&...
Does this sound good?
Fully BC.
Constraints: This is disabled to work together with multiValue as it is designed as alternative config.
If someone has ideas how to combine them, that could be a future PR maybe?

Allow not filter for value instead of long array list.

---

composer.json
src/Command/Bake/FilterCollectionCommand.php
src/Plugin.php
tests/TestCase/Command/Bake/FilterCollectionCommandTest.php

Closes #305.
While this fixes the issue, until https://github.com/cakephp/bake/pull/727 is merged the command will show up as `bake_filter_collection` instead of `filter_collection`. I don't think that's a biggie as it's a dev tool only.

Fix error when bake plugin is not loaded.

---

src/Model/Filter/Boolean.php
tests/TestCase/Model/Filter/BooleanTest.php

Fix return value for Boolean::process().

---

docs/README.md

also fixed header
I found this out when trying to set a custom one but it still used the "inherited" one.

Add example for combining

---

src/Command/Bake/FilterCollectionCommand.php
templates/bake/FilterCollection/filter_collection.twig
tests/TestCase/Command/Bake/FilterCollectionCommandTest.php
tests/comparisons/Filter/testCustomName.php
tests/comparisons/Filter/testDefault.php
tests/comparisons/Filter/testEmpty.php
tests/comparisons/Filter/testPrefix.php

Remove "Filter" from baked collections.

---

tests/TestCase/Model/Behavior/SearchBehaviorTest.php

As we did the same in https://github.com/cakephp/cakephp/pull/15472 I replaced phpunits deprecated `->at()` method with `->once()`

replace phpunits at() method with once()

---

composer.json

Auto created via toolbox app.
- Runs https://github.com/ergebnis/composer-normalize over composer.json

Run composer normalize over composer.json

---

.phive/phars.xml
docs/filters-and-examples.md
phpstan.neon
src/Model/Filter/Base.php
src/Model/Filter/Boolean.php
src/Model/Filter/Compare.php
src/Model/Filter/Escaper/DefaultEscaper.php
src/Model/Filter/Escaper/SqlserverEscaper.php
src/Model/Filter/Exists.php
src/Model/Filter/Finder.php
src/Model/Filter/Like.php
src/Model/Filter/Value.php
tests/TestApp/Model/Table/FinderArticlesTable.php
tests/TestCase/Model/Filter/BaseTest.php
tests/TestCase/Model/Filter/BooleanTest.php
tests/TestCase/Model/Filter/CallbackTest.php
tests/TestCase/Model/Filter/ExistsTest.php
tests/TestCase/Model/Filter/FinderTest.php
tests/TestCase/Model/Filter/LikeTest.php
tests/TestCase/Model/Filter/ValueTest.php

With stricter method signatures this becomes necessary for Finder usage.
Resolves 
- https://github.com/FriendsOfCake/search/issues/338
- https://github.com/FriendsOfCake/search/issues/341
We can release a new minor 7.1.0

Add casting for Finder.

---

docs/filters-and-examples.md
src/Command/Bake/FilterCollectionCommand.php
src/Manager.php
src/Model/Behavior/SearchBehavior.php
src/Model/Filter/Base.php
src/Model/Filter/Callback.php
src/Model/Filter/Compare.php
src/Model/Filter/Like.php
src/Model/SearchTrait.php
tests/TestCase/Command/Bake/FilterCollectionCommandTest.php
tests/TestCase/Controller/Component/SearchComponentTest.php
tests/TestCase/ManagerTest.php
tests/TestCase/Model/Behavior/SearchBehaviorTest.php
tests/TestCase/Model/Filter/BaseTest.php
tests/TestCase/Model/Filter/BooleanTest.php
tests/TestCase/Model/Filter/CallbackTest.php
tests/TestCase/Model/Filter/CompareTest.php
tests/TestCase/Model/Filter/ExistsTest.php
tests/TestCase/Model/Filter/FinderTest.php
tests/TestCase/Model/Filter/LikeTest.php
tests/TestCase/Model/Filter/ValueTest.php
tests/TestCase/View/Helper/SearchHelperTest.php

This enables exact quote matches
```php
$filter->setConfig('multiValueSeparator', ' ');
$filter->setConfig('multiValueExactMatching', true);
$filter->setArgs(['fields' => 'value1 "value2 and 3" value4']);
$this->assertEquals(['value1', 'value2 and 3', 'value4'], $filter->value());
$filter->setConfig('multiValueSeparator', ' ');
$filter->setConfig('multiValueExactMatching', '*');
$filter->setArgs(['fields' => 'value1 *value2 and 3* value4']);
$this->assertEquals(['value1', 'value2 and 3', 'value4'], $filter->value());
```
Changes are in the 1st commit.
The 2nd is just to make CS happy again.

multiValueExactMatching feature

---

docs/filters-and-examples.md
src/Model/Filter/Base.php

@dereuromark I just did minor refactoring to keep all string splitting code in the same method. While the string parsing might only be used in `Like` or `Value` there might be custom filters relying on it too, so keeping it in `Base` for now to avoid any BC break. Don't want to do a new major for it.

Minor refactoring of multi value parsing

---

docs/additional-docs.md
docs/filters-and-examples.md
src/Controller/Component/SearchComponent.php
tests/TestCase/Controller/Component/SearchComponentTest.php

Resolves https://github.com/FriendsOfCake/search/issues/347
```php
$callable = function ($value, array $params) use ($minPrice, $maxPrice): bool {
$minValue = $minPrice ? (int)$minPrice->price : 0;
$maxValue = $maxPrice ? (int)ceil((float)$maxPrice->price) : 0;
if (!$minPrice && !$maxPrice) {
return true;
}
if (empty($params['price_min']) || empty($params['price_max'])) {
return true;
}
if ((string)$minValue === $params['price_min'] && (string)$maxValue === $params['price_max']) {
return true;
}
return false;
};
$this->Search->setConfig('emptyValues', [
'price_min' => $callable,
'price_max' => $callable,
]);
```	
With this I dont need hacks anymore in the controller actions (that still dont properly work fully)

Fix up empty via callable for more dynamic use cases.

---

src/Controller/Component/SearchComponent.php
tests/TestCase/Controller/Component/SearchComponentTest.php

This PR fixes a deprecation warning that appears when using the **FriendsOfCake/search** plugin with CakePHP 5.2.

Fixed deprecation warning in CakePHP 5.2

---

src/Controller/Component/SearchComponent.php
tests/TestCase/Controller/Component/SearchComponentTest.php

This allows for use cases like saving the searches made by the user.

Use Form::execute() instead of Form::validate().
